stages:
  prepare:
    cmd: python src/prepare.py data/data.csv
    deps:
    - data/data.csv
    - src/prepare.py
    outs:
    - data/prepare

  preprocessing:
    cmd: python src/preprocessing.py data/prepare/prepared_data.csv
    deps:
    - data/prepare
    - src/preprocessing.py
    params:
    - preprocessing.seed
    - preprocessing.split
    outs:
    - data/processed

  train:
    cmd: python src/train.py data/processed model/xgb_model.pkl
    deps:
    - data/processed
    - src/train.py
    params:
    - train.learning_rate
    - train.max_depth
    - train.n_estimators
    - train.seed
    outs:
    - model/xgb_model.pkl

  evaluate:
    cmd: python src/evaluate.py model/xgb_model.pkl data/processed
    deps:
    - data/processed
    - model/xgb_model.pkl
    - src/evaluate.py
    outs:
    - eval

metrics:
- eval/metrics.json
plots:
- eval/plots/images/importance.png
- eval/plots/images/actual_vs_predicted.png
artifacts:
  xgb_model:
    path: model/xgb_model.pkl
    type: model
